name: Vulnerable Issue Logger

on:
  issues:
    types: [opened, edited]

jobs:
  log-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Log Issue Title
        run: |
          echo "Das Issue hat den Titel: ${{ github.event.issue.title }}"
